# See https://hub.docker.com/_/postgres/
# See https://www.baeldung.com/dockerizing-spring-boot-application

version: '3.1'

services:

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
    networks:
      - spring-cloud-network

  app-server:
    container_name: app-server
    build:
      context: .
      dockerfile: Dockerfile
    image: app-server
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
